[project]
name = "diabetes-ft"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "kagglehub>=0.3.13",
    "pandas>=2.3.3",
    "pytorch-tabular[all]>=1.1.1",
    "scikit-learn>=1.7.2",
    "xgboost>=3.1.1",
]
